spring:

  datasource:
    url: jdbc:mysql://localhost:3306/web_link_checker_database
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  messages:
    basename: i18n/messages

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate.format_sql: true
      user_sql_comments: true

  mvc:
    view:
      suffix: ftl
      prefix: /templates/

